### ISSUE TITLE
Room titles formatting in "Escape Rooms"

### ISSUE THREAD

**Issue by FibreKitty** [FibreKitty/FuzzyLogic-Web#1]
[imported from GitLab]

Is it possible for us to add ability to adjust text size of "Casino" "Time Pirates" and "Vet office" room titles in "Escape Rooms" page.
They are also unnecessarily hyperlinked to themselves (clicking a room title takes you to the top of the page.)

@roweland commented a week ago:
I'm not afraid to edit CSS for this. I just need to know where to go.

**Comment by FibreKitty** [comment]
Do you want each room title to have its own formatting, or do you want a consistent format across all room titles?

**Comment by FibreKitty** [comment]
@tommytran0, do you want each room title to have its own formatting, or do you want a consistent format across all room titles?

**Comment by tommytran0** [comment]
Allowing each room to have it's own formatting would allow us the most creative freedom. Is it significantly more work to implement that?

**Comment by FibreKitty** [comment]
@tommytran0 
Fonts are a tricky business because not everyone might have the one you want. Fonts with websites should always come with the corresponding TTF file for compatibility. This could be implemented in theory, but this is more work than I think you realize.

**Comment by tommytran0** [comment]
If fixing the font is best for compatability, can you at least leave the sizing up to us? as well as italic/bold/underline and font color?

**Comment by FibreKitty** [comment]
@tommytran0 
Italic/bold/underline/font color are fine, but enabling custom font sizes for this won't do what you think it does. You can force font sizes with websites, but it rarely works in practice, since everything is relative.

Is font size something you really want/need? I would advise against it, especially since it ruins the visual flow.

**Comment by tommytran0** [comment]
Italic/bold/underline/color are vital.

So even making it so a change of font for a given heading site wide would
still have that problem? What about placing limits on how big or small we
can make the font?

On Aug 13, 2017 10:18 AM, "Tim Campbell" <notifications@github.com> wrote:

@tommytran0 <https://github.com/tommytran0>
Italic/bold/underline/font color are fine, but enabling custom font sizes
for this won't do what you think it does. You can force font sizes with
websites, but it rarely works in practice, since everything is relative.

Is font size something you really want/need? I would advise against it,
especially since it ruins the visual flow.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FibreKitty/FuzzyLogic-Web/issues/1#issuecomment-322044889>,
or mute the thread

**Comment by FibreKitty** [comment]
Again, I strongly advice against modifying title font and sizing too much unless it will all be the same consistent size and font throughout the page. Violating this is going against basic and fundamental design principles, and not something I want to encourage.

I would suggest perhaps uploading pictures for the rooms that have fonts/titles/whatever included in them as an alternative, as that will be visually much more coherent.

However if this is an absolute necessity, I can see what I can do, but results of this cannot be guaranteed across platforms.

**Comment by FibreKitty** [comment]
@tommytran0 
Again, I strongly advice against modifying title font and sizing too much unless it will all be the same consistent size and font throughout the page. Violating this is going against basic and fundamental design principles, and not something I want to encourage.

I would suggest perhaps uploading pictures for the rooms that have fonts/titles/whatever included in them as an alternative, as that will be visually much more coherent.

However if this is an absolute necessity, I can see what I can do, but results of this cannot be guaranteed across platforms.

**Comment by tommytran0** [comment]
Okay, then. Let's just go with bold/italic/color/underline then.

**Comment by FibreKitty** [comment]
Done, can adjust room title formatting somewhat
